firmware: added initial support for boot os cp/m from external usb storage
This is a work in progress feature.  If RomWBW or MSX ROM images are detected
at boot, expect unchanged behaviour.  Otherwise, system now attempt to load
and boot CP/M 2.2 OS from an external USB disk image.  Requires the Linear RAM
module for operation.

1. New top level directory - operating-system
2. New apps (via submodule xmodem80) XR.COM and XS.COM

See firmware/src/fbios/readme.txt for details of current progress

diff --git a/apps/Makefile b/apps/Makefile
--- a/apps/Makefile
+++ b/apps/Makefile
@@ -1,9 +1,9 @@
-SHELL := /bin/sh
+SHELL := /bin/bash
 BIN=./bin/
 MAKEFLAGS += --no-print-directory
 
 # Define the sub directories to be built
-BINARIES := CFILES VHBIOS CPMEXMPL CUBE DHRY EXE EZ80 HWADL HWZ80 I2CSCAN LINE MATRIX8 MBROT VFYADL VFYADL VFYZ80 WHET WOLF3D SUPHDMI SHWS2812
+BINARIES := CFILES VHBIOS CPMEXMPL CUBE DHRY EXE EZ80 HWADL HWZ80 I2CSCAN LINE MATRIX8 MBROT VFYADL VFYADL VFYZ80 WHET WOLF3D SUPHDMI SHWS2812 XR XS
 
 # Default target
 all: $(BINARIES:%=$(BIN)%.COM)
@@ -33,6 +33,20 @@ common-libs:
 
 z88dk:
 	@docker run --rm -w /host/${PWD} -v /:/host/ -u $(USER_ID):$(GROUP_ID) -it z88dk/z88dk
+
+bin/XR.COM:
+	@if ! command -v z80asm &> /dev/null; then \
+		echo -e "\033[0;31mError: to assemble the XR and XS utils, you need to have z80asm installed. Please install z80asm (eg: sudo apt install z80asm).\033[0m" >&2; \
+		exit 0; \
+	fi; \
+	cd xmodem80 && z80asm xr.z80 --list --output ../bin/XR.COM 2> ../bin/XR.COM.lst
+
+bin/XS.COM:
+	@if ! command -v z80asm &> /dev/null; then \
+		echo -e "\033[0;31mError: to assemble the XR and XS utils, you need to have z80asm installed. Please install z80asm (eg: sudo apt install z80asm).\033[0m" >&2; \
+		exit 0; \
+	fi;
+	cd xmodem80 && z80asm xs.z80 --list --output ../bin/XS.COM 2> ../bin/XS.COM.lst
 
 clean:
 	@rm -rf $(BIN)
